# Generated by Django 4.2.9 on 2024-01-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("creator", models.CharField(max_length=100)),
                ("time_watched", models.DateTimeField()),
                ("url", models.URLField()),
            ],
        ),
    ]
