# Generated by Django 4.2.9 on 2024-01-05 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyser", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videorecord",
            old_name="name",
            new_name="title",
        ),
    ]
