# Generated by Django 4.2.9 on 2024-01-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyser", "0003_creator_alter_videorecord_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="videorecord",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
