# Generated by Django 4.2.9 on 2024-01-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyser", "0005_alter_creator_name_alter_creator_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="times_watched",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="videorecord",
            name="times_watched",
            field=models.IntegerField(default=0),
        ),
    ]
