# Generated by Django 4.2.9 on 2024-01-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyser", "0006_creator_times_watched_videorecord_times_watched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videorecord",
            name="title",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="videorecord",
            name="url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
