# Generated by Django 4.2.9 on 2024-01-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyser", "0007_alter_videorecord_title_alter_videorecord_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videorecord",
            name="times_watched",
        ),
        migrations.AlterField(
            model_name="videorecord",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="videorecord",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
