# Generated by Django 4.2.9 on 2024-01-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyser", "0008_remove_videorecord_times_watched_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="times_watched",
            field=models.IntegerField(default=1),
        ),
    ]
